# This workflow started from:
# https://github.com/denoland/setup-deno

name: Devops

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: deno run -A --unstable util/build.ts
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A --unstable
